LABELS = (
    {"attributes": {"type":  "rect",
                    "class": "car.occluded.0",
                    "id":    ["car.occluded.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "car.occluded.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "car.occluded.1",
                    "id":    ["car.occluded.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "car.occluded.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "car.occluded.2",
                    "id":    ["car.occluded.2"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "car.occluded.2"
    },
    {"attributes": {"type":  "rect",
                    "class": "car.occluded.3",
                    "id":    ["car.occluded.3"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "car.occluded.3"
    },
    {"attributes": {"type":  "rect",
                    "class": "car.truncated.0",
                    "id":    ["car.truncated.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "car.truncated.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "car.truncated.1",
                    "id":    ["car.truncated.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "car.truncated.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "var.occluded.0",
                    "id":    ["var.occluded.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "var.occluded.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "var.occluded.1",
                    "id":    ["var.occluded.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "var.occluded.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "var.occluded.2",
                    "id":    ["var.occluded.2"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "var.occluded.2"
    },
    {"attributes": {"type":  "rect",
                    "class": "var.occluded.3",
                    "id":    ["var.occluded.3"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "var.occluded.3"
    },
    {"attributes": {"type":  "rect",
                    "class": "var.truncated.0",
                    "id":    ["var.truncated.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "var.truncated.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "var.truncated.1",
                    "id":    ["var.truncated.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "var.truncated.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "truck.occluded.0",
                    "id":    ["truck.occluded.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "truck.occluded.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "truck.occluded.1",
                    "id":    ["truck.occluded.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "truck.occluded.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "truck.occluded.2",
                    "id":    ["truck.occluded.2"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "truck.occluded.2"
    },
    {"attributes": {"type":  "rect",
                    "class": "truck.occluded.3",
                    "id":    ["truck.occluded.3"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "truck.occluded.3"
    },
    {"attributes": {"type":  "rect",
                    "class": "truck.truncated.0",
                    "id":    ["truck.truncated.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "truck.truncated.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "truck.truncated.1",
                    "id":    ["truck.truncated.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "truck.truncated.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "pedestrian.occluded.0",
                    "id":    ["pedestrian.occluded.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "pedestrian.occluded.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "pedestrian.occluded.1",
                    "id":    ["pedestrian.occluded.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "pedestrian.occluded.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "pedestrian.occluded.2",
                    "id":    ["pedestrian.occluded.2"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "pedestrian.occluded.2"
    },
    {"attributes": {"type":  "rect",
                    "class": "pedestrian.occluded.3",
                    "id":    ["pedestrian.occluded.3"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "pedestrian.occluded.3"
    },
    {"attributes": {"type":  "rect",
                    "class": "pedestrian.truncated.0",
                    "id":    ["pedestrian.truncated.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "pedestrian.truncated.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "pedestrian.truncated.1",
                    "id":    ["pedestrian.truncated.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "pedestrian.truncated.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "person_sitting.occluded.0",
                    "id":    ["person_sitting.occluded.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "person_sitting.occluded.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "person_sitting.occluded.1",
                    "id":    ["person_sitting.occluded.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "person_sitting.occluded.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "person_sitting.occluded.2",
                    "id":    ["person_sitting.occluded.2"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "person_sitting.occluded.2"
    },
    {"attributes": {"type":  "rect",
                    "class": "person_sitting.occluded.3",
                    "id":    ["person_sitting.occluded.3"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "person_sitting.occluded.3"
    },
    {"attributes": {"type":  "rect",
                    "class": "person_sitting.truncated.0",
                    "id":    ["person_sitting.truncated.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "person_sitting.truncated.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "person_sitting.truncated.1",
                    "id":    ["person_sitting.truncated.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "person_sitting.truncated.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "cyclist.occluded.0",
                    "id":    ["cyclist.occluded.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "cyclist.occluded.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "cyclist.occluded.1",
                    "id":    ["cyclist.occluded.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "cyclist.occluded.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "cyclist.occluded.2",
                    "id":    ["cyclist.occluded.2"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "cyclist.occluded.2"
    },
    {"attributes": {"type":  "rect",
                    "class": "cyclist.occluded.3",
                    "id":    ["cyclist.occluded.3"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "cyclist.occluded.3"
    },
    {"attributes": {"type":  "rect",
                    "class": "cyclist.truncated.0",
                    "id":    ["cyclist.truncated.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "cyclist.truncated.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "cyclist.truncated.1",
                    "id":    ["cyclist.truncated.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "cyclist.truncated.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "tram.occluded.0",
                    "id":    ["tram.occluded.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "tram.occluded.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "tram.occluded.1",
                    "id":    ["tram.occluded.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "tram.occluded.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "tram.occluded.2",
                    "id":    ["tram.occluded.2"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "tram.occluded.2"
    },
    {"attributes": {"type":  "rect",
                    "class": "tram.occluded.3",
                    "id":    ["tram.occluded.3"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "tram.occluded.3"
    },
    {"attributes": {"type":  "rect",
                    "class": "tram.truncated.0",
                    "id":    ["tram.truncated.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "tram.truncated.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "tram.truncated.1",
                    "id":    ["tram.truncated.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "tram.truncated.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "misc.occluded.0",
                    "id":    ["misc.occluded.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "misc.occluded.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "misc.occluded.1",
                    "id":    ["misc.occluded.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "misc.occluded.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "misc.occluded.2",
                    "id":    ["misc.occluded.2"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "misc.occluded.2"
    },
    {"attributes": {"type":  "rect",
                    "class": "misc.occluded.3",
                    "id":    ["misc.occluded.3"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "misc.occluded.3"
    },
    {"attributes": {"type":  "rect",
                    "class": "misc.truncated.0",
                    "id":    ["misc.truncated.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "misc.truncated.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "misc.truncated.1",
                    "id":    ["misc.truncated.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "misc.truncated.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "dont_care.occluded.0",
                    "id":    ["dont_care.occluded.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "dont_care.occluded.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "dont_care.occluded.1",
                    "id":    ["dont_care.occluded.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "dont_care.occluded.1"
    },
    {"attributes": {"type":  "rect",
                    "class": "dont_care.occluded.2",
                    "id":    ["dont_care.occluded.2"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "dont_care.occluded.2"
    },
    {"attributes": {"type":  "rect",
                    "class": "dont_care.occluded.3",
                    "id":    ["dont_care.occluded.3"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "dont_care.occluded.3"
    },
    {"attributes": {"type":  "rect",
                    "class": "dont_care.truncated.0",
                    "id":    ["dont_care.truncated.0"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "dont_care.truncated.0"
    },
    {"attributes": {"type":  "rect",
                    "class": "dont_care.truncated.1",
                    "id":    ["dont_care.truncated.1"],
     "item":     "sloth.items.RectItem",
     "inserter": "sloth.items.RectItemInserter",
     "text":     "dont_care.truncated.1"
    },
)